### ISSUE TITLE
Invoking an Alias with non-image URLs triggers an exception

### ISSUE THREAD

**Issue by ThomazFB** [the-orange-team/orange-bot#20]
```
2021-05-04T20:34:33.703996+00:00 app[worker.1]: [ERROR]  web-api:WebClient:0 downloading image failed [json-pointer:/blocks/0/image_url]
2021-05-04T20:34:33.792668+00:00 app[worker.1]: [ERROR]  bolt-app Error: An API error occurred: invalid_blocks
2021-05-04T20:34:33.792670+00:00 app[worker.1]: at Object.platformErrorFromResult (/app/node_modules/@slack/web-api/dist/errors.js:51:33)
2021-05-04T20:34:33.792670+00:00 app[worker.1]: at WebClient.apiCall (/app/node_modules/@slack/web-api/dist/WebClient.js:156:28)
2021-05-04T20:34:33.792671+00:00 app[worker.1]: at processTicksAndRejections (internal/process/task_queues.js:93:5) {
2021-05-04T20:34:33.792671+00:00 app[worker.1]: code: 'slack_webapi_platform_error',
2021-05-04T20:34:33.792672+00:00 app[worker.1]: data: {
2021-05-04T20:34:33.792672+00:00 app[worker.1]: ok: false,
2021-05-04T20:34:33.792672+00:00 app[worker.1]: error: 'invalid_blocks',
2021-05-04T20:34:33.792673+00:00 app[worker.1]: errors: [ 'downloading image failed [json-pointer:/blocks/0/image_url]' ],
2021-05-04T20:34:33.792673+00:00 app[worker.1]: response_metadata: { messages: [Array], scopes: [Array], acceptedScopes: [Array] }
2021-05-04T20:34:33.792673+00:00 app[worker.1]: }
2021-05-04T20:34:33.792674+00:00 app[worker.1]: }
```

**Comment by ThomazFB** [comment]
Fixed starting from 79cd4198e7097ddd6ae103214dc75ce6d2f77d0e
